### ISSUE TITLE
Plugin deprecated ?

### ISSUE THREAD

**Issue by gaetan29** [AutohomeCorp/autohome-compareQueries-datasource#40]
Hi,
I am using Grafana v10.1.5  ... so far, your plugin is working pretty well.
But  get an alert message regarding future deprecation as follow..

"Angular plugin
This data source plugin uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana."

Will you upgrade your excellent plugin ?

I am using it here:
https://www.rvn-dashboard.com:3000/d/RFxvsAvnk/rvn-hd-dashboard?orgId=1&viewPanel=502

Thanks & regards.

**Comment by gaetan29** [comment]
https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

**Comment by Candelax98** [comment]
+1 here.
This plugin is awesome and I would hate it if it stopped working because of the deprecation.
Thanks for your kind work

**Comment by salman-akh** [comment]
Hi the plugin has stopped working with newer version of grafana. Is there any update on the plugin? I hope there is, it has been very handy plugin.

**Comment by Antartic0** [comment]
Good morning. Any news about this plugin? I didn´t find any alternative and it´s useful for me the comparison with others timeshifts. Is it on schedule the migration to react?

**Comment by leoswing** [comment]
I'm working on a version with react upgrade support, which codes and function has been test already. The release version will publish to github soon.

**Comment by leoswing** [comment]
> Good morning. Any news about this plugin? I didn´t find any alternative and it´s useful for me the comparison with others timeshifts. Is it on schedule the migration to react?

@Antartic0 @salman-akh You could wait for my release version on github with a new repo comes with react support

**Comment by leoswing** [comment]
> > Good morning. Any news about this plugin? I didn´t find any alternative and it´s useful for me the comparison with others timeshifts. Is it on schedule the migration to react?
> 
> @Antartic0 @salman-akh You could wait for my release version on github with a new repo comes with react support

Anyone wish to use the React version could refer to repo:  https://github.com/leoswing/autohome-compareQueries-datasource-rc

[autohome-compareQueries-datasource-rc](https://github.com/leoswing/autohome-compareQueries-datasource-rc) is totally written with React, and works well, updates could see the [changelog](https://github.com/leoswing/autohome-compareQueries-datasource-rc/blob/main/CHANGELOG.md)

- Restructure codebase migrate from Angular to React
- Compare Functions keep with the origin
- Alias displayName support enhance

@gaetan29 @Candelax98 @Antartic0 @salman-akh welcome to use this new version zip files~~

Test passed in Grafana 9.x and 10.4.2

**Comment by leoswing** [comment]
> https://github.com/leoswing/autohome-compareQueries-datasource-rc

Hi,  @gaetan29  you could use the new repo which has migrate to React~  links as below

https://github.com/leoswing/autohome-compareQueries-datasource-rc

**Comment by gaetan29** [comment]
Hi,
V 1.0.0(2024-06-18) installed on Grafana V10.4.2 and working nicely.
Great job !

Question: Shall I upgrade to Grafana V10.4.4 or even V11 ?

Regards

**Comment by leoswing** [comment]
> Hi, V 1.0.0(2024-06-18) installed on Grafana V10.4.2 and working nicely. Great job !
> 
> Question: Shall I upgrade to Grafana V10.4.4 or even V11 ?
> 
> Regards

Hi, I think it depens on your demand. If higher version of grafana could satisfied your funcional needs, that would be fine~

**Comment by Antartic0** [comment]
Hi, 
I´ve removed the previous version from /var/lib/grafana/plugins and clone via git to same path but it doesn´t appear when I try to create a new datasource. Do I need another step in the middle? I´ve got the line in grafana.ini also.

**Comment by gaetan29** [comment]
Here is what I did:

1- I disabled old version in Grafana / Plugins / uninstall
2- I then downloaded the zip file into a temp folder ( wget -c https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/download/1.0.0/autohome-comparequeries-datasource.zip)
3- I then installed the plugin (sudo grafana-cli --pluginUrl autohome-comparequeries-datasource.zip plugins install autohome-comparequeries-datasource)
4- Finally I restarted Grafana Server (sudo service grafana-server restart)


Rgds

**Comment by Antartic0** [comment]
> Here is what I did:
> 
> 1- I disabled old version in Grafana / Plugins / uninstall 2- I then downloaded the zip file into a temp folder ( wget -c https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/download/1.0.0/autohome-comparequeries-datasource.zip) 3- I then installed the plugin (sudo grafana-cli --pluginUrl autohome-comparequeries-datasource.zip plugins install autohome-comparequeries-datasource) 4- Finally I restarted Grafana Server (sudo service grafana-server restart)
> 
> Rgds

I´ve tried but It doesn´t work for me now:
`Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json for in /var/lib/grafana/plugins/autohome-comparequeries-datasource
`

**Comment by Antartic0** [comment]
Now it works.
`✔ Downloaded and extracted autohome-comparequeries-datasource v1.0.0 zip successfully to /var/lib/grafana/plugins/autohome-comparequeries-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.`

But the datasource is not available or I can´t see it. Can be related to the permissions of the plugin. Currently is under root:root but I have other plugin as OCI with grafana user as owner.

**Comment by Antartic0** [comment]
> Now it works. `✔ Downloaded and extracted autohome-comparequeries-datasource v1.0.0 zip successfully to /var/lib/grafana/plugins/autohome-comparequeries-datasource
> 
> Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.`
> 
> But the datasource is not available or I can´t see it. Can be related to the permissions of the plugin. Currently is under root:root but I have other plugin as OCI with grafana user as owner.

It works... finally it´s an issue on rocky linux image with the permissions.

Thnx for the plugin, @leoswing . Great work!

**Comment by leoswing** [comment]
> > Now it works. `✔ Downloaded and extracted autohome-comparequeries-datasource v1.0.0 zip successfully to /var/lib/grafana/plugins/autohome-comparequeries-datasource
> > Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.`
> > But the datasource is not available or I can´t see it. Can be related to the permissions of the plugin. Currently is under root:root but I have other plugin as OCI with grafana user as owner.
> 
> It works... finally it´s an issue on rocky linux image with the permissions.
> 
> Thnx for the plugin, @leoswing . Great work!

@Antartic0 That would be fine if it solved your problem ～ I also encountered some issues due to linux image permissions. And in docker mode for using this plugin, I would do some tricks as below:

The example like docker image with plugin [autohome-compareQueries-datasource](https://github.com/leoswing/autohome-compareQueries-datasource-rc) is as below:

```bash
FROM node:14-alpine AS build-stage
WORKDIR /plugins
COPY ./plugins/autohome-comparequeries-datasource.zip autohome-comparequeries-datasource.zip

RUN \
  unzip autohome-comparequeries-datasource.zip && \
  rm -rf autohome-comparequeries-datasource.zip

FROM grafana/grafana:10.4.2

# Disable Login form or not
ENV GF_AUTH_DISABLE_LOGIN_FORM "false"
# Allow anonymous authentication or not
ENV GF_AUTH_ANONYMOUS_ENABLED "false"
# Role of anonymous user
ENV GF_AUTH_ANONYMOUS_ORG_ROLE "Admin"
# Install plugins here our in your own config file
# ENV GF_INSTALL_PLUGINS="<list of plugins seperated by ,"

# Add configuration file
ADD ./grafana.ini /etc/grafana/grafana.ini

RUN chmod -R 755 /var/lib/grafana/plugins/

COPY --from=build-stage /plugins/ /var/lib/grafana/plugins/autohome-comparequeries-datasource
```

**Comment by leoswing** [comment]
> Hi, V 1.0.0(2024-06-18) installed on Grafana V10.4.2 and working nicely. Great job !
> 
> Question: Shall I upgrade to Grafana V10.4.4 or even V11 ?
> 
> Regards

@gaetan29 @Candelax98 @Antartic0 @salman-akh  I've tested on Grafana 11.0.0, and seems this plugin queries does not work, and I've updated the plugin codes to fit with Grafana 11. 

> Grafana 11 Breaking changes can see [query-filtering-changes](https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/#data-sources-query-filtering-changes)

You could download the 1.1.0 version to replace the old version 1.0.0

The plugin with version **1.1.0** suit with Grafana 8， 9， 10.x， and the latest 11.0.0 ~ 

I recommend all of you to upgrade to the 1.1.0 version ~ details can see [v1.1.0](https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.1.0)

Use the latest signed plugin with the link: https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource/

**Comment by leoswing** [comment]
@gaetan29 @Antartic0 @salman-akh @Candelax98 Hi guys, could you please update your old version with the latest version 1.1.0 ?

https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.1.0

The 1.1.0 version could fix the filterQuery issue, and totally suit with Grafana 11, also Grafana 10.x and 9.x is  tested ok.

**Comment by gaetan29** [comment]
Hi,
V 1.1.0 installed and working on V 10.4.2... I haven't yet installed latest version.

That said, it still show as Version 1.0.0 when installing Version 1.1.0
See below:

sudo grafana-cli --pluginUrl autohome-comparequeries-datasource.zip plugins install autohome-comparequeries-datasource
✔ Downloaded and extracted autohome-comparequeries-datasource v1.0.0 zip successfully to /var/lib/grafana/plugins/autohome-comparequeries-datasource

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.



sudo grafana-cli plugins ls
autohome-comparequeries-datasource @ 1.0.0

**Comment by leoswing** [comment]
> Hi, V 1.1.0 installed and working on V 10.4.2... I haven't yet installed latest version.
> 
> That said, it still show as Version 1.0.0 when installing Version 1.1.0 See below:
> 
> sudo grafana-cli --pluginUrl autohome-comparequeries-datasource.zip plugins install autohome-comparequeries-datasource ✔ Downloaded and extracted autohome-comparequeries-datasource v1.0.0 zip successfully to /var/lib/grafana/plugins/autohome-comparequeries-datasource
> 
> Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
> 
> sudo grafana-cli plugins ls autohome-comparequeries-datasource @ 1.0.0

Nice! We hav upgrade Grafana to 11.0.0 and it works well too.

**Comment by Antartic0** [comment]
I will update shortly because I am working on other project now. Next week I will update because I´ve noted something when I use the plugin to show comparison between 1 day and 1 week ago. It´s like the query I´ve created disappears suddenly and the query appears void. 

Thnx!

**Comment by leoswing** [comment]
@gaetan29 @Antartic0 @salman-akh @Candelax98 Hi guys, I feel so sorry about the plugin issue:  when reopen dashboard editor mode, the data which binding to the compareQueries plugin lost. I've fix that with the release version [1.2.0](https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.2.0)

Could you help to use the fix version:  https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.2.0

to replace the old version? Much appreciated if you could use the latest version.

Sorry about the issue with binding form~

**Comment by gaetan29** [comment]
Version 1.2.0 now installed and running.... But it is showing as Version 1.1.0 despite I have loaded your latest version.
![Screenshot_2024-06-24 10 48 35_mFeYY8](https://github.com/AutohomeCorp/autohome-compareQueries-datasource/assets/788375/5bbf705c-9f8c-40d0-964c-206b32e40105)

**Comment by leoswing** [comment]
> Version 1.2.0 now installed and running.... But it is showing as Version 1.1.0 despite I have loaded your latest version. ![Screenshot_2024-06-24 10 48 35_mFeYY8](https://private-user-images.githubusercontent.com/788375/342268388-5bbf705c-9f8c-40d0-964c-206b32e40105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTk3NTcsIm5iZiI6MTcxOTIxOTQ1NywicGF0aCI6Ii83ODgzNzUvMzQyMjY4Mzg4LTViYmY3MDVjLTlmOGMtNDBkMC05NjRjLTIwNmIzMmU0MDEwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwODU3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzE3NDFlMTlmMzYwZWE5MjRlOTc2ZjIyYjJkNWQ4YTlhNDAyODAzNjk2ZGJmNDZlYjcyNjdkNDZkMDMxOTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-JvMyI_O9VGqpZ2TQuwFtdLBer-pRVsfruszrrfOAgs)

Let me see, I think this due to github action fail, and the version remain the older one.. let me republish the 1.2.0 again.

**Comment by gaetan29** [comment]
Now sorted, thanks
![Screenshot_2024-06-24 11 21 48_2qsj50](https://github.com/AutohomeCorp/autohome-compareQueries-datasource/assets/788375/a8e8a27b-cc55-44eb-a24d-2a66c0f7b6b4)

**Comment by leoswing** [comment]
> Version 1.2.0 now installed and running.... But it is showing as Version 1.1.0 despite I have loaded your latest version. ![Screenshot_2024-06-24 10 48 35_mFeYY8](https://private-user-images.githubusercontent.com/788375/342268388-5bbf705c-9f8c-40d0-964c-206b32e40105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMjExOTEsIm5iZiI6MTcxOTIyMDg5MSwicGF0aCI6Ii83ODgzNzUvMzQyMjY4Mzg4LTViYmY3MDVjLTlmOGMtNDBkMC05NjRjLTIwNmIzMmU0MDEwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwOTIxMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjJiNTY1ZTk4NDQ4MDBiMmQzODkzY2Q0ZDI1NzI0OGI0MmEzMTc0ZjAwZmI4ZWUyN2I1ZjQ2OTY4MjljYWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NcCjYzkzr0tDY0znUTFWISnhMZcb-teK9Umnl7dFNRM)

@gaetan29 Hi , version 1.2.0 is released  and upgrade now.  see version [1.2.0](https://github.com/leoswing/autohome-compareQueries-datasource-rc/releases/tag/1.2.0)

**Comment by Antartic0** [comment]
Is there any way to update without conflicts or the best way to apply an update over this plugin? 
Thanks in advance

**Comment by gaetan29** [comment]
I personnaly upgrade that way:
1- sudo grafana-cli plugins remove autohome-comparequeries-datasource
2- sudo service grafana-server restart
3- download the zip plugin on your server (wget -c ...)
4-  sudo grafana-cli --pluginUrl autohome-comparequeries-datasource.zip plugins install autohome-comparequeries-datasource
5- sudo service grafana-server restart

**Comment by leoswing** [comment]
For all of all, I've updated the plugin source and release the breaking change version 2.0.0, the changes of version 2.0.0 is as below:

- Plugin id refactor to `leoswing-comparequeries-datasource` for the reason to sign the plugin for public
- Try to sign the signature as public plugin in Grafana, and it's still **Waiting For Review**

Anyone who upgrades with the version 2.0.0 needs to upgrade the Grafana property:

```ini
[plugins]
allow_loading_unsigned_plugins = leoswing-comparequeries-datasource
```

And anyone use the breaking change 2.0.0, should also upgrade the origin dashboards... and you guys could keep the both

Also you can use  `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS` env instead for environment variables changed.

**Comment by leoswing** [comment]
Hi  @gaetan29 @Antartic0 @salman-akh @Candelax98 sorry to interrupt you all,

the latest plugin with version 2.0.1 has been signed with public level, and welcome to use this new plugin with id `leoswing-comparequeries-datasource`.

With this latest 2.0.1 version, we've improved the key features as below:

- Compatible with Grafana 11
- Resolves issues with undefined data points
- Fix Query ref unchange issue
- Introduces support for timeShift aliases
- Form ui  effect  with Grafana ui components

Plugin details could see the grafana plugins market: https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource/

**Comment by MisterMartin** [comment]
Thanks so much for upgrading that plugin and getting it signed. It works great!

**Comment by gaetan29** [comment]
Thank you, brilliant plugin.
V2.0.1 working nicely.

**Comment by netforce** [comment]
V2.0.1 working fine so far on Grafana v10.4.3

**Comment by leoswing** [comment]
Hi @MisterMartin @gaetan29 @netforce @Antartic0 , 

I've updated the plugin with version 2.0.3, which supports the amount field with variable, it supports variable input format if you use variable in that amount field. Could you please help to upgrade with the latest one? Plugin has updated in Grafana store.

https://grafana.com/grafana/plugins/leoswing-comparequeries-datasource/


<img width="910" alt="image" src="https://github.com/user-attachments/assets/037fb6c6-6cef-405f-a42c-88ae24578ec3" />
